routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('challange/new',function(){
	$categories = \App\Category::all();
	return view('challange.new',['categories'=>$categories]);
})->name('challange.create');

Route::get('challange/{challange}/post',function(\App\Challange $challange){
	return view('post.submit',['challange'=>$challange]);
})->name('post.submit');

Route::apiResources([
    'challange' => 'ChallangeController',
    'post' => 'PostController',
    'invite' => 'InviteController'
]);

Route::get('post/{post}/file','PostController@file')->name('post.file');

Auth::routes();

app/Challange.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Challange extends Model
{
	public function posts(){
		return $this->hasMany('App\Post', 'challange_id', 'id');	
	}

	public function category(){
		return $this->belongsTo('App\Category','category_id','id');
	}

	public function invites(){
		return $this->hasMany('App\Invite','challange_id','id');
	} 
}

app/Http/Controllers/ChallangeController.php
<?php

namespace App\Http\Controllers;

use App\Challange;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Http\File;

// Facades
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;

class ChallangeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $challanges = Challange::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required|max:150',
            'type'=>'required|max:10',
            'category'=>'required|integer',
        ]);
        if($request->type == 'video')
            $this->validate($request,[
                'file'=>'required|mimetypes:video/*'
            ]);
        else
            $this->validate($request,[
                'file'=>'required|mimetypes:image/*'
            ]);

        $user = Auth::user();
        $c = new Challange;
        $c->title = $request->get('title');
        $c->description = $request->get('description');
        $c->category_id = $request->get('category');
        $c->user_id = $user->id;
        $c->save();
        $p = new Post;
        $p->title = $request->get('title');
        $p->description = $request->get('description');
        $p->type = $request->get('type');
        $p->file = $request->file('file')->store('files');
        $p->user_id = $user->id;
        $p->challange_id = $c->id;
        $p->save();
        $i = new \App\Invite;
        $i->sender_id = $user->id;
        $i->receiver_id = $user->id;
        $i->challange_id = $c->id;
        $i->save(); 
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Challange  $challange
     * @return \Illuminate\Http\Response
     */
    public function show(Challange $challange)
    {
        return view('challange.show')->with('challange',$challange);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Challange  $challange
     * @return \Illuminate\Http\Response
     */
    public function edit(Challange $challange)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Challange  $challange
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Challange $challange)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Challange  $challange
     * @return \Illuminate\Http\Response
     */
    public function destroy(Challange $challange)
    {
        //
    }
}

resources/views/challange/new.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">New Challange</div>
            <div class="card-body">
                <form action="{{route('challange.store')}}" method='post' enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input name='title' type="text" class="form-control" id="title" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <label for="title">Description</label>
                        <textarea name='description' class="form-control" placeholder="Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="challangeCategory">Category</label>
                        <select name='category' class="form-control" id="challangeCategory">
                          @foreach($categories as $category)
                            <option value='{{$category->id}}'>{{$category->name}}</option>
                          @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <div class="custom-file">
                            <input name='file' type="file" class="custom-file-input">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                    <div class='form-group'>
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" type="radio" name="type" id="type1" value="video" required="" checked>
                          <label class="form-check-label" for="type1">Video</label>
                        </div>
                        <div class="form-check form-check-inline">
                          <input class="form-check-input" type="radio" name="type" id="type2" value="photo" required="">
                          <label class="form-check-label" for="type2">Photo</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/challange/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <span class='badge badge-primary'>{{$challange->category->name}}</span>
    <h1>{{$challange->title}}</h1>
    <p class='text-muted'>{{$challange->description}}</p>
    <hr/>
    <h4>Invite User</h4>
    <form class="form-inline" method="post" action="{{route('invite.store')}}">
        @csrf
        <input hidden name='challange' value='{{$challange->id}}'>
        <label class="sr-only" for="inlineFormInputGroupUsername2">Email</label>
        <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">User</div>
            </div>
            <input name='receiver' type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-primary mb-2">Invite</button>
    </form>
    <hr/>
    <h3>Posts
        @canPost($challange)
        <a class='btn btn-primary float-right' href="{{route('post.submit',$challange)}}">Submit Entry</a>
        @endcanPost
    </h3>

<div class='card-columns'>
    @foreach($challange->posts as $post)
    
    <div class='card'>
        @if($post->type == 'photo')
            <img class="card-img-top" src="{{route('post.file',$post)}}"/>
        @endif
        <div class='card-body'>
        <h4 class='card-title'>{{$post->title}}</h4>
        <small class='text-muted'>{{$post->user->name}}</small>
        
        @if($post->type == 'video')
        <video width="320" height="240" controls>
          <source src="{{route('post.file',$post)}}" type='video/mp4'>
        Your browser does not support the video tag.
        </video>
        @endif
        
    </div>
</div>
    @endforeach
    </div>
</div>
@endsection